# 1ª Avaliação de Programação Estatística com Python - 10/12/2019



* Nome: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
   * Matrícula: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Questão 1 (1,0 ponto)** Implemente uma função que gere $C$ matrizes $\mathbf{X}_c^{n_c \times p}$, $c = 1, \ldots, C$, aleatoriamente, onde $n_c$ é a quantidade de linhas da matriz $\mathbf{X}_c$. As $p$ colunas de cada matriz $\mathbf{X}_c$ devem ser sorteadas de distribuições normais com médias e variâncias diferentes. A função deve então concatenar todas as matrizes geradas e retornar a matriz $\mathbf{X}^{n \times p}$, onde $n = \sum_{c=1}^C n_c$. <ins>Dica 1</ins>: A função pode receber como parâmetros uma lista com a quantidade de linhas de cada matriz $\mathbf{X}_c$, uma lista com as médias das normais usadas para gerar as colunas de cada matriz e outra lista com as variâncias correspondentes. <ins>Dica 2</ins>: considere usar a função *numpy.random.multivariate_normal*.

In [20]:
import numpy as np
def Q01(C, p, n, param):
    np.random.seed(26112000)
    Xc = []

    for i in range(C): # Gerando as 'C' Matrizes aleatorias
        # param[0][i] parametro de localização // param[1][i] parametro de escala
        Xc.append(np.random.normal(param[0][i], param[1][i], (n[i],p))) 
        # array de matrizes gerados , com parametros de localização, e escala antes informados como parametros
        # possuindo n[i] linhas, informado como parametro da função

    Xnp = np.vstack((Xc)) # Concatenação das matrizes do arrey gerado pelo for

    return Xnp # Matriz gerada aleatoriamente 

# Parametro de locação
mu = [
    [1],
    [0.7],
    [1]
]

# Parametro de escala
covar = [
    [0.9],
    [0.3],
    [0.1]
]

Q1 = Q01(3,2, [28, 30,40], param = (mu, covar))

print(Q1)


[[ 2.17647332  0.43153427]
 [ 0.75788747  0.2511219 ]
 [ 0.21238821  2.02135922]
 [ 0.76892883  1.56120292]
 [ 0.09572293  0.80872846]
 [ 1.87696162  1.13387206]
 [ 1.08876098  0.97253802]
 [ 1.79992027  0.81092352]
 [ 0.3608241   0.32427351]
 [ 1.60351491  1.94360588]
 [-0.19548028 -0.01123783]
 [-0.77042199  1.33789193]
 [ 1.47356845  1.38669575]
 [ 0.97174205  2.1087363 ]
 [ 1.34605433  1.35480915]
 [ 1.75539372  2.0909584 ]
 [-0.01915118  0.76017994]
 [ 0.28916832  0.30967243]
 [ 2.40295217 -0.89519049]
 [ 1.68011741  0.38130194]
 [ 2.28332002  0.91445911]
 [ 0.57679777  0.78431668]
 [ 0.39474912 -0.19810206]
 [ 0.80246446  0.12301272]
 [ 1.25262198  2.53374251]
 [ 1.83494188  0.86336456]
 [ 1.08390389  0.89307543]
 [ 1.67366313  1.26126108]
 [ 0.64209896  0.58476707]
 [ 1.06680452  0.86844008]
 [ 0.47354714  0.39557851]
 [ 0.43716007  0.36695391]
 [ 0.59831722  0.38860597]
 [ 0.42059139  0.52518749]
 [ 1.43143833  0.84574555]
 [ 0.65203049  0.64332784]
 [ 0.75551404  0.22253127]
 

**Questão 2 (1,0 ponto)** Faça uma função que recebe uma matriz $\mathbf{X}^{n \times p}$ e um inteiro $k$ e retorna uma matriz $W^{k \times p}$, cujas linhas foram selecionadas aleatoriamente e sem reposição de $\mathbf{X}^{n \times p}$.

In [21]:
def Q02(Xnp, k):
    np.random.seed(26112000)
    Wkp = []

    for j in range(k): # for para a seleção das k linhas da matriz Xnp
    
        Wkp.append(Xnp[np.random.choice(len(Xnp[:, 1]), size = 1, replace = True)])
        # Crianção do array com tamanho k, composto de k matrizes geradas aleatoriamente

    Wkp = np.vstack(Wkp) # Concatenação dos k arrays de matrizes aleatorias
    
    return Wkp # Matriz k por p, feita por concatenação de matrizes geradas aleatoriamente
Q2 = Q02(Q1, 5)

print(Q2)

[[1.08390389 0.89307543]
 [0.43716007 0.36695391]
 [0.47354714 0.39557851]
 [1.0491578  1.10530016]
 [1.28820568 1.08817799]]


**Questão 3 (1,0 ponto)** Faça uma função que recebe duas matrizes $\mathbf{X}^{n \times p}$ e $\mathbf{W}^{k \times p}$ e retorna a matriz de distâncias Euclidianas $\mathbf{D}^{n \times k}$ entre as linhas de $\mathbf{X}$ e as de $\mathbf{W}$.

In [22]:
def Q03(Xnp, Wkp):
    
    Dnk = np.zeros((len(Xnp), len(Wkp))) # Matriz composta de zeros, onde possui len(Xnp) linhas e len(Wkp) colunas

    for i in range(len(Xnp)): # for para fixar a primeira linha de Xnp
        for j in range(len(Wkp)): # for para varrer as linhas de Wkp, fixando a linha i da matriz Xnp
            Dnk[i,j] = np.sqrt(np.sum((Xnp[i,:] - Wkp[j,:])**(2))) # Calculo da distancia euclidiana

    return Dnk # Matriz de distancias de Xnp, para  cada linha de Wkp

Q3 = Q03(Q1, Q2)

print(Q3)


[[1.18605573 1.74051177 1.70330573 1.3133167  1.1046268 ]
 [0.71999378 0.34100311 0.31893124 0.90247377 0.99090882]
 [1.42568015 1.66960454 1.64662288 1.24070445 1.42415254]
 [0.73864987 1.23947618 1.20246855 0.53514073 0.70242511]
 [0.99177418 0.55834046 0.55986071 0.99849528 1.22478861]
 [0.82880853 1.63131602 1.58576466 0.82829675 0.59052646]
 [0.0796109  0.88955937 0.84342774 0.13854313 0.23054455]
 [0.72071381 1.43325657 1.38988387 0.80641298 0.58199816]
 [0.91998914 0.0874574  0.13338248 1.04106    1.20149351]
 [1.17201102 1.96117696 1.91656357 1.00502153 0.91168898]
 [1.56671833 0.73706363 0.78300525 1.67205892 1.84662913]
 [1.90693109 1.549508   1.56058123 1.83438533 2.07371766]
 [0.6288875  1.45396553 1.40796165 0.50922281 0.35138613]
 [1.22082415 1.82197249 1.78412662 1.00641804 1.06849824]
 [0.53096222 1.34236611 1.2966851  0.38781734 0.27283447]
 [1.37325242 2.17023765 2.12542787 1.2125557  1.10626996]
 [1.11103182 0.60236755 0.61293217 1.12267183 1.34787413]
 [0.98588219 0

**Questão 4 (1,0 ponto)** Qual função de NumPy pode ser usada para obter para cada linha da matriz $\mathbf{D}$, retornada pela função da questão acima, a coluna que representa a menor distância da linha correspondente em $\mathbf{X}$ para as linhas de $\mathbf{W}$? Use a função para retornar essa informação.

In [23]:
Q4 = np.argmin(Q3, axis = 1) # Atribui 0, caso a menor distancia da linha de X para a de W esteja na primeira coluna
                             # Atribui 1, caso a menor distancia da linha de X para a de W esteja na segunda coluna
                             # ... idem para j colunas 
print(Q4)

[4 2 3 3 1 4 0 4 1 4 1 1 4 3 4 4 1 1 0 0 4 2 1 2 3 4 0 4 2 0 2 1 2 2 4 2 2
 0 1 0 2 1 3 2 2 1 0 0 0 2 0 2 2 2 2 1 3 1 3 3 3 4 0 3 0 3 4 3 3 3 0 3 3 0
 0 3 0 4 3 3 3 3 0 0 0 3 3 0 0 3 0 0 3 0 0 3 0 3]


**Questão 5 (2,0 pontos)** Faça uma função que atualiza as linhas de $\mathbf{W}$, fazendo com que cada linha assuma o valor médio das linhas de $\mathbf{X}$ para as quais a mesma foi a mais próxima. A função deve retornar a matriz $\mathbf{W}$ modificada. Use a função de NumPy mencionada na Questão 4.

In [28]:
def Q05(Xnp, Wkp, Dnk, c):
    k = np.argmin(Dnk, axis = 1) # Array com a localizacação das menores distancias da linhas

    for i in range(c):
        X = Xnp[k == i,:] # quem são os X que possuem as menores distancia para com W
        Wkp[i,:] = np.apply_along_axis(func1d = np.mean, arr = X, axis = 0) # Wkp esta assumindo por linha o valor medio                                                                             # das linhas de X  para as quais a mesma foi                                                                             # a mais proxima
    
    return Wkp # Matriz atualizada, com os valores medios das linhas de X mais proximas de W

Q5 = Q05(Q1, Q2, Q3, 4)

print(Q5)

[[1.06772777 0.76136681]
 [0.1826148  0.43229101]
 [0.63560841 0.41503296]
 [0.92596984 1.21905325]
 [1.28820568 1.08817799]]


**Questão 6 (1,5 pontos)** Implemente uma classe, chamada *KMeans*, cujo construtor define os seguintes atributos: $k$ e $t_{max}$. A classe deve conter um método *fit*, que recebe como parâmetro uma matriz $\mathbf{X}$. O método *fit* irá então seguir os seguintes passos:

  1. Use a função implementada na Questão 2 para obter a matriz $\mathbf{W}$ (note que o segundo parâmetro da função receberá como argumento um dos atributos definidos no construtor);
  2. Repita as operações abaixo $t_{max}$ vezes (note que isso é um atributo):
    1. Use a função da Questão 3 para calcular as distâncias entre $\mathbf{X}$ e $\mathbf{W}$
    2. Use a função da Questão 5 para atualizar as linhas de $\mathbf{W}$

Ao final do método *fit*, a matriz $\mathbf{W}$ resultante deve ser guardada como um atributo.

In [29]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax # Atributos k, e tmax, para o uso no Monte Carlo

    def fit(self,X, k): # Função para ajustar o modelo
        W = Q02(X,k) # Criação das matrizes, k por p, de forma aleatoria

        for i in range(self.tmax): # for para a geração do monte carlo
            dists = Q03(X, W) # Calculando as distancias euclidianas, da linha i de X  para cada linhas W
            new_W = Q05(X, W, dists, k) # W atualizado com as medias das menores distancias X , para W
        
        return new_W # Matriz da ultima iteração do Monte Carlo ,  'treinada'
X = Q1
k = 4
tmax = 100
km = KMeans(k, tmax) 

print(km.fit(X, k)) # AJustando o modelo


[[2.00781238 0.52003785]
 [0.07029236 0.6914937 ]
 [0.62802553 0.35260132]
 [1.04013245 1.10178154]]


**Questão 7 (1,0 ponto)** Adicione o método *predict* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função de NumPy mencionada na Questão 4 para retornar os índices das linhas de $\mathbf{W}$ mais próximas às linhas de $\mathbf{X}$.

In [42]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W) # Calculo das distancias Euclidianas de X linha i, para cada linha W
        return np.argmin(dists , axis = 1) # Retorna as menores distancias de X, para um Wi, on de Wi são as linhas deW
    
X = Q1
k = 5
tmax = 100

km = KMeans(k, tmax)

# lista de medias para a geração das matrizes aleatorias
mu1 = [
    [2],
    [1.444]
]

# lista de variancias para a geração das matrizes aleatorias
covar1 = [
    [0.4625],
    [0.9584]
]
X1 = Q01(2,2,[15,30], param = (mu1, covar1)) # Geração da matriz Aleatorias

print(km.fit(X,k)) # AJustando o modelo
print()
print(km.predict(X1)) # Retornando os indices das menores distancias de X

[[1.03390562 0.99314854]
 [0.07029236 0.6914937 ]
 [0.62802553 0.35260132]
 [1.09409828 2.04326754]
 [2.00781238 0.52003785]]

[4 3 3 3 3 3 3 3 3 3 0 3 3 3 3 3 1 2 4 4 4 0 2 0 3 4 0 3 0 3 2 2 2 0 4 0 4
 4 1 3 4 2 3 0 4]


 **Questão 8 (1,5 ponto)** Adicione o método *score* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função da Questão 3 para calcular as distâncias para a matrix $\mathbf{W}$. Após isso, o método retornará o somatório das menores distâncias.

In [ ]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)

    def score(self, X):
        d = Q03(X, self.W) # Calculo da matriz de distancias euclidianas
        d = np.apply_along_axis(min, 1, d) # 
        return np.sum(d)
X = Q1
k = 5
tmax = 100
km = KMeans(k, tmax)
X1 = Q01(2,2, param = ((0,1), (0,1)))
X2 = Q01(2,2, param = ((0,1), (0,1)))
km.fit(X,k)
print(km.fit(X,k), km.predict(X1), km.score(X2))