# 1ª Avaliação de Programação Estatística com Python - 10/12/2019



   * Nome: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
   * Matrícula: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Questão 1 (1,0 ponto)** Implemente uma função que gere $C$ matrizes $\mathbf{X}_c^{n_c \times p}$, $c = 1, \ldots, C$, aleatoriamente, onde $n_c$ é a quantidade de linhas da matriz $\mathbf{X}_c$. As $p$ colunas de cada matriz $\mathbf{X}_c$ devem ser sorteadas de distribuições normais com médias e variâncias diferentes. A função deve então concatenar todas as matrizes geradas e retornar a matriz $\mathbf{X}^{n \times p}$, onde $n = \sum_{c=1}^C n_c$. <ins>Dica 1</ins>: A função pode receber como parâmetros uma lista com a quantidade de linhas de cada matriz $\mathbf{X}_c$, uma lista com as médias das normais usadas para gerar as colunas de cada matriz e outra lista com as variâncias correspondentes. <ins>Dica 2</ins>: considere usar a função *numpy.random.multivariate_normal*.

In [2]:
import numpy as np
def Q01(C, p, param):
    np.random.seed(26112000)
    Xc = []

    for i in range(C):
        Xc.append(np.random.normal(param[0][i], param[1][i], (np.random.randint(50),p)))
    
    Xnp = np.vstack((Xc))

    return Xnp

mu = [
    [12,5],
    [8.5,7],
    [1,4]
]
covar = [
    [0.954,0.2],
    [0.37,0.87],
    [0.123,0.234]
]

Q1 = Q01(3,2, param = (mu, covar))

print(Q1)


[[11.68055331  5.04768358]
 [12.45683333  5.29632818]
 [12.24575666  4.77580595]
 [10.2681405   5.17864599]
 [10.43242332  5.00649975]
 [12.38184639  4.73684924]
 [11.80454636  4.89499821]
 [12.14739861  4.97853278]
 [11.99271585  4.72487881]
 [10.59406235  4.98880846]
 [11.4808153   5.07367705]
 [12.22683777  4.88755301]
 [12.99467139  5.03182678]
 [11.03808977  4.95545514]
 [11.37189215  5.07532705]
 [12.39556353  4.6804301 ]
 [11.15660674  4.90756748]
 [12.16731706  4.95264912]
 [11.16593028  4.97784988]
 [13.64452818  5.05445754]
 [12.69940793  5.12963262]
 [12.48255319  5.15733615]
 [15.29102379  4.96994811]
 [12.26664515  5.08491387]
 [12.33207714  5.04441407]
 [11.4949317   4.73631252]
 [ 8.82233092  5.77578054]
 [ 8.25494046  7.61915213]
 [ 8.88199729  5.91596589]
 [ 8.19093968  6.61300143]
 [ 7.93371352  6.21785835]
 [ 8.28255842  6.35128895]
 [ 8.50546326  6.70104885]
 [ 8.14486376  7.23237372]
 [ 8.29296866  6.4075656 ]
 [ 7.77186477  7.2853933 ]
 [ 8.40327237  7.76179447]
 

**Questão 2 (1,0 ponto)** Faça uma função que recebe uma matriz $\mathbf{X}^{n \times p}$ e um inteiro $k$ e retorna uma matriz $W^{k \times p}$, cujas linhas foram selecionadas aleatoriamente e sem reposição de $\mathbf{X}^{n \times p}$.

In [3]:
def Q02(Xnp, k):
    np.random.seed(26112000)
    Wkp = []

    for j in range(k):
        
        Wkp.append(Xnp[np.random.choice(len(Xnp[:, 1]), size = 1, replace = True)])

    Wkp = np.vstack(Wkp)
    
    return Wkp
Q2 = Q02(Q1, 5)

print(Q2)

[[8.82233092 5.77578054]
 [8.28255842 6.35128895]
 [7.93371352 6.21785835]
 [0.99170569 4.20230174]
 [8.81153599 8.42823189]]


**Questão 3 (1,0 ponto)** Faça uma função que recebe duas matrizes $\mathbf{X}^{n \times p}$ e $\mathbf{W}^{k \times p}$ e retorna a matriz de distâncias Euclidianas $\mathbf{D}^{n \times k}$ entre as linhas de $\mathbf{X}$ e as de $\mathbf{W}$.

In [4]:
def Q03(Xnp, Wkp):
    
    Dnk = np.zeros((len(Xnp), len(Wkp)))

    for i in range(len(Xnp)):
        for j in range(len(Wkp)):
            Dnk[i,j] = np.sqrt(np.sum((Xnp[i,:] - Wkp[j,:])**(2)))

    return Dnk

Q3 = Q03(Q1, Q2)

print(Q3)


[[ 2.94950172  3.63947197  3.92531749 10.72222616  4.4338885 ]
 [ 3.66598995  4.30552126  4.61604059 11.51720651  4.80593524]
 [ 3.56648188  4.26486659  4.54678251 11.26865433  5.01339075]
 [ 1.5642682   2.3059982   2.55529091  9.32767339  3.5611101 ]
 [ 1.78443001  2.53581882  2.776858    9.47490812  3.78622854]
 [ 3.70803568  4.40574369  4.68820585 11.40267715  5.13550603]
 [ 3.1095637   3.81119165  4.09063636 10.83500585  4.63053466]
 [ 3.41930974  4.10139601  4.39216005 11.18266601  4.79879186]
 [ 3.34002022  4.05098484  4.32486854 11.01341507  4.88208248]
 [ 1.93864832  2.68317043  2.9305323   9.63451329  3.87389129]
 [ 2.74963425  3.44400047  3.72707417 10.52524182  4.28696748]
 [ 3.51846771  4.20712046  4.4945109  11.25601005  4.91942001]
 [ 4.23814726  4.89336174  5.19807325 12.0315958   5.38833828]
 [ 2.36273592  3.0889003   3.35124064 10.07457559  4.12525394]
 [ 2.64403055  3.34246341  3.62304431 10.41683465  4.21869583]
 [ 3.73734984  4.43943469  4.71929986 11.41387666  5.18

**Questão 4 (1,0 ponto)** Qual função de NumPy pode ser usada para obter para cada linha da matriz $\mathbf{D}$, retornada pela função da questão acima, a coluna que representa a menor distância da linha correspondente em $\mathbf{X}$ para as linhas de $\mathbf{W}$? Use a função para retornar essa informação.

In [5]:
Q4 = np.argmin(Q3, axis = 1)
print(Q4)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 1 2 1 1 1 1 1 4
 1 1 1 2 1 1 0 2 0 4 4 4 4 0 1 4 1 0 2 1 4 4 4 4 4 1 1 0 4 1 0 1 1 1 2 3 3
 3 3 3 3 3 3 3 3 3 3 3 3]


**Questão 5 (2,0 pontos)** Faça uma função que atualiza as linhas de $\mathbf{W}$, fazendo com que cada linha assuma o valor médio das linhas de $\mathbf{X}$ para as quais a mesma foi a mais próxima. A função deve retornar a matriz $\mathbf{W}$ modificada. Use a função de NumPy mencionada na Questão 4.

In [6]:
def Q05(Xnp, Wkp, Dnk, c):
    k = np.argmin(Dnk, axis = 1)
    
    for i in range(c):
        X = Xnp[k == i,:]
        Wkp[i,:] = np.apply_along_axis(func1d = np.mean, arr = X, axis = 0)
    
    return Wkp

Q5 = Q05(Q1, Q2, Q3, 4)

print(Q5)

[[11.21570545  5.11216807]
 [ 8.42408005  6.76454073]
 [ 7.81256795  6.61388484]
 [ 1.00496024  4.0107249 ]
 [ 8.81153599  8.42823189]]


**Questão 6 (1,5 pontos)** Implemente uma classe, chamada *KMeans*, cujo construtor define os seguintes atributos: $k$ e $t_{max}$. A classe deve conter um método *fit*, que recebe como parâmetro uma matriz $\mathbf{X}$. O método *fit* irá então seguir os seguintes passos:

  1. Use a função implementada na Questão 2 para obter a matriz $\mathbf{W}$ (note que o segundo parâmetro da função receberá como argumento um dos atributos definidos no construtor);
  2. Repita as operações abaixo $t_{max}$ vezes (note que isso é um atributo):
    1. Use a função da Questão 3 para calcular as distâncias entre $\mathbf{X}$ e $\mathbf{W}$
    2. Use a função da Questão 5 para atualizar as linhas de $\mathbf{W}$

Ao final do método *fit*, a matriz $\mathbf{W}$ resultante deve ser guardada como um atributo.

In [7]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)

        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        return new_W
X = Q1
k = 4
tmax = 100
km = KMeans(k, tmax)

print(km.fit(X, k))


[[12.00819876  4.97493775]
 [ 8.27958572  7.70023714]
 [ 8.47463985  6.1269791 ]
 [ 1.00496024  4.0107249 ]]


**Questão 7 (1,0 ponto)** Adicione o método *predict* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função de NumPy mencionada na Questão 4 para retornar os índices das linhas de $\mathbf{W}$ mais próximas às linhas de $\mathbf{X}$.

In [12]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)
    
X = Q1
k = 2
tmax = 100
km = KMeans(k, tmax).fit(X,k)
mu = [
    [4.5124,5],
    [5,2],
    [1,1]
]
covar = [
    [0.324,0.924],
    [0.2624,0.745],
    [0.356,0.245]
]
X1 = Q01(3,2, param = (mu, covar))

print(km.fit(X,k))
print(km.predict(X1))


AttributeError: 'numpy.ndarray' object has no attribute 'fit'

**Questão 8 (1,5 ponto)** Adicione o método *score* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função da Questão 3 para calcular as distâncias para a matrix $\mathbf{W}$. Após isso, o método retornará o somatório das menores distâncias.

In [ ]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)

    def score(self, X):
        d = Q03(X, self.W)
        d = np.apply_along_axis(min, 1, d)
        return np.sum(d)
X = Q1
k = 5
tmax = 100
km = KMeans(k, tmax)
X1 = Q01(2,2, param = ((0,1), (0,1)))
X2 = Q01(2,2, param = ((0,1), (0,1)))
km.fit(X,k)
print(km.fit(X,k), km.predict(X1), km.score(X2))