# 1ª Avaliação de Programação Estatística com Python - 10/12/2019



* Nome: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
   * Matrícula: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Questão 1 (1,0 ponto)** Implemente uma função que gere $C$ matrizes $\mathbf{X}_c^{n_c \times p}$, $c = 1, \ldots, C$, aleatoriamente, onde $n_c$ é a quantidade de linhas da matriz $\mathbf{X}_c$. As $p$ colunas de cada matriz $\mathbf{X}_c$ devem ser sorteadas de distribuições normais com médias e variâncias diferentes. A função deve então concatenar todas as matrizes geradas e retornar a matriz $\mathbf{X}^{n \times p}$, onde $n = \sum_{c=1}^C n_c$. <ins>Dica 1</ins>: A função pode receber como parâmetros uma lista com a quantidade de linhas de cada matriz $\mathbf{X}_c$, uma lista com as médias das normais usadas para gerar as colunas de cada matriz e outra lista com as variâncias correspondentes. <ins>Dica 2</ins>: considere usar a função *numpy.random.multivariate_normal*.

In [30]:
import numpy as np
def Q01(C, p, n, param):
    np.random.seed(26112000)
    Xc = []

    for i in range(C): # Gerando as 'C' Matrizes aleatorias
        # param[0][i] parametro de localização // param[1][i] parametro de escala
        Xc.append(np.random.normal(param[0][i], param[1][i], (n[i],p))) 
        # array de matrizes gerados , com parametros de localização, e escala antes informados como parametros
        # possuindo n[i] linhas, informado como parametro da função

    Xnp = np.vstack((Xc)) # Concatenação das matrizes do arrey gerado pelo for

    return Xnp # Matriz gerada aleatoriamente 

# Parametro de locação
mu = [
    [1],
    [0.7],
    [1]
]

# Parametro de escala
covar = [
    [0.9],
    [0.3],
    [0.1]
]

Q1 = Q01(3,2, [12, 8,3], param = (mu, covar))

print(Q1)


[[ 2.17647332  0.43153427]
 [ 0.75788747  0.2511219 ]
 [ 0.21238821  2.02135922]
 [ 0.76892883  1.56120292]
 [ 0.09572293  0.80872846]
 [ 1.87696162  1.13387206]
 [ 1.08876098  0.97253802]
 [ 1.79992027  0.81092352]
 [ 0.3608241   0.32427351]
 [ 1.60351491  1.94360588]
 [-0.19548028 -0.01123783]
 [-0.77042199  1.33789193]
 [ 0.85785615  0.82889858]
 [ 0.69058068  1.06957877]
 [ 0.81535144  0.81826972]
 [ 0.95179791  1.0636528 ]
 [ 0.36028294  0.62005998]
 [ 0.46305611  0.46989081]
 [ 1.16765072  0.06826984]
 [ 0.9267058   0.49376731]
 [ 1.14259111  0.99049546]
 [ 0.95297753  0.97603519]
 [ 0.9327499   0.86687755]]


**Questão 2 (1,0 ponto)** Faça uma função que recebe uma matriz $\mathbf{X}^{n \times p}$ e um inteiro $k$ e retorna uma matriz $W^{k \times p}$, cujas linhas foram selecionadas aleatoriamente e sem reposição de $\mathbf{X}^{n \times p}$.

In [39]:
def Q02(Xnp, k):
    np.random.seed(26112000)
    Wkp = []

    for j in range(k): # for para a seleção das k linhas da matriz Xnp
    
        Wkp.append(Xnp[np.random.choice(len(Xnp[:, 1]), size = 1, replace = True)])
        # Crianção do array com tamanho k, composto de k matrizes geradas aleatoriamente

    Wkp = np.vstack(Wkp) # Concatenação dos k arrays de matrizes aleatorias
    
    return Wkp # Matriz k por p, feita por concatenação de matrizes geradas aleatoriamente
Q2 = Q02(Q1, 5)

print(Q2)

[[0.21238821 2.02135922]
 [0.3608241  0.32427351]
 [0.95179791 1.0636528 ]
 [1.60351491 1.94360588]
 [0.46305611 0.46989081]]


**Questão 3 (1,0 ponto)** Faça uma função que recebe duas matrizes $\mathbf{X}^{n \times p}$ e $\mathbf{W}^{k \times p}$ e retorna a matriz de distâncias Euclidianas $\mathbf{D}^{n \times k}$ entre as linhas de $\mathbf{X}$ e as de $\mathbf{W}$.

In [40]:
def Q03(Xnp, Wkp):
    
    Dnk = np.zeros((len(Xnp), len(Wkp))) # Matriz composta de zeros, onde possui len(Xnp) linhas e len(Wkp) colunas

    for i in range(len(Xnp)): # for para fixar a primeira linha de Xnp
        for j in range(len(Wkp)): # for para varrer as linhas de Wkp, fixando a linha i da matriz Xnp
            Dnk[i,j] = np.sqrt(np.sum((Xnp[i,:] - Wkp[j,:])**(2))) # Calculo da distancia euclidiana

    return Dnk # Matriz de distancias de Xnp, para  cada linha de Wkp

Q3 = Q03(Q1, Q2)

print(Q3)


[[2.52689012 1.81881471 1.37818856 1.61698543 1.71384649]
 [1.85237945 0.40374555 0.83534886 1.89197986 0.36713127]
 [0.         1.70356483 1.20992904 1.39329792 1.57158793]
 [0.72213661 1.30251443 0.53009171 0.91802285 1.13336677]
 [1.21822993 0.55224563 0.89322493 1.8871628  0.49974455]
 [1.88638228 1.71875617 0.92782468 0.85465897 1.5620499 ]
 [1.36676814 0.97475073 0.16450163 1.09906523 0.8025963 ]
 [1.99634983 1.51915306 0.88497663 1.14958444 1.37967717]
 [1.70356483 0.         0.94653673 2.04120498 0.17792072]
 [1.39329792 2.04120498 1.09501255 0.         1.86345979]
 [2.0731154  0.64964792 1.57214411 2.65665158 0.81557031]
 [1.19709792 1.51892726 1.74391757 2.44999303 1.50827522]
 [1.35594662 0.70829889 0.25285291 1.34111123 0.53362314]
 [1.06515448 0.81499652 0.26128443 1.26387195 0.64139931]
 [1.34572992 0.67128784 0.28076769 1.37389342 0.49545925]
 [1.20992904 0.94653673 0.         1.09501255 0.76903956]
 [1.40908212 0.29578697 0.73936766 1.8158743  0.18197006]
 [1.57158793 0

**Questão 4 (1,0 ponto)** Qual função de NumPy pode ser usada para obter para cada linha da matriz $\mathbf{D}$, retornada pela função da questão acima, a coluna que representa a menor distância da linha correspondente em $\mathbf{X}$ para as linhas de $\mathbf{W}$? Use a função para retornar essa informação.

In [41]:
Q4 = np.argmin(Q3, axis = 1) # Atribui 0, caso a menor distancia da linha de X para a de W esteja na primeira coluna
                             # Atribui 1, caso a menor distancia da linha de X para a de W esteja na segunda coluna
                             # ... idem para j colunas 
print(Q4)

[2 4 0 2 4 3 2 2 1 3 1 0 2 2 2 2 4 4 4 4 2 2 2]


**Questão 5 (2,0 pontos)** Faça uma função que atualiza as linhas de $\mathbf{W}$, fazendo com que cada linha assuma o valor médio das linhas de $\mathbf{X}$ para as quais a mesma foi a mais próxima. A função deve retornar a matriz $\mathbf{W}$ modificada. Use a função de NumPy mencionada na Questão 4.

In [43]:
def Q05(Xnp, Wkp, Dnk, c):
    k = np.argmin(Dnk, axis = 1) # Array com a localizacação das menores distancias da linhas
    for i in range(c):
        X = Xnp[k == i,:] # quem são os X que possuem as menores distancia para com W
        Wkp[i,:] = np.apply_along_axis(func1d = np.mean, arr = X, axis = 0) # Wkp esta assumindo por linha o valor medio                                                                             # das linhas de X  para as quais a mesma foi                                                                             # a mais proxima
    
    return Wkp # Matriz atualizada, com os valores medios das linhas de X mais proximas de W

Q5 = Q05(Q1, Q2, Q3, 4)

print(Q5)

[[-0.27901689  1.67962557]
 [ 0.08267191  0.15651784]
 [ 1.10708983  0.94454607]
 [ 1.74023827  1.53873897]
 [ 0.46305611  0.46989081]]


**Questão 6 (1,5 pontos)** Implemente uma classe, chamada *KMeans*, cujo construtor define os seguintes atributos: $k$ e $t_{max}$. A classe deve conter um método *fit*, que recebe como parâmetro uma matriz $\mathbf{X}$. O método *fit* irá então seguir os seguintes passos:

  1. Use a função implementada na Questão 2 para obter a matriz $\mathbf{W}$ (note que o segundo parâmetro da função receberá como argumento um dos atributos definidos no construtor);
  2. Repita as operações abaixo $t_{max}$ vezes (note que isso é um atributo):
    1. Use a função da Questão 3 para calcular as distâncias entre $\mathbf{X}$ e $\mathbf{W}$
    2. Use a função da Questão 5 para atualizar as linhas de $\mathbf{W}$

Ao final do método *fit*, a matriz $\mathbf{W}$ resultante deve ser guardada como um atributo.

In [34]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax # Atributos k, e tmax, para o uso no Monte Carlo

    def fit(self,X, k): # Função para ajustar o modelo
        W = Q02(X,k) # Criação das matrizes, k por p, de forma aleatoria

        for i in range(self.tmax): # for para a geração do monte carlo, com tmax iterações
            dists = Q03(X, W) # Calculando as distancias euclidianas, da linha i de X  para cada linhas W
            new_W = Q05(X, W, dists, k) # W atualizado com as medias das menores distancias X , para W
        
        return new_W # Matriz da ultima iteração do Monte Carlo ,  'treinada'
X = Q1
k = 4
tmax = 100
km = KMeans(k, tmax) 

print(km.fit(X, k)) # AJustando o modelo


[[-0.27901689  1.67962557]
 [ 0.429992    0.36158667]
 [ 1.09205783  0.90698118]
 [ 1.74023827  1.53873897]]


**Questão 7 (1,0 ponto)** Adicione o método *predict* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função de NumPy mencionada na Questão 4 para retornar os índices das linhas de $\mathbf{W}$ mais próximas às linhas de $\mathbf{X}$.

In [44]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W) # Calculo das distancias Euclidianas de X linha i, para cada linha W
        return np.argmin(dists , axis = 1) # Retorna as menores distancias de X, para um Wi, on de Wi são as linhas deW
    
X = Q1
k = 5
tmax = 100

km = KMeans(k, tmax)

# lista de medias para a geração das matrizes aleatorias
mu1 = [
    [2],
    [1.444]
]

# lista de variancias para a geração das matrizes aleatorias
covar1 = [
    [0.4625],
    [0.9584]
]
X1 = Q01(2,2,[15,30], param = (mu1, covar1)) # Geração da matriz Aleatorias

print(km.fit(X,k)) # AJustando o modelo
print()
print(km.predict(X1)) # Retornando os indices das menores distancias de X

[[-0.27901689  1.67962557]
 [-0.19548028 -0.01123783]
 [ 1.10708983  0.94454607]
 [ 1.74023827  1.53873897]
 [ 0.5903043   0.43373026]]

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 4 2 3 3 2 4 2 3 3 3 3 2 3 4 4 2 4 3 2 2
 3 4 3 2 4 3 2 4]


**Questão 8 (1,5 ponto)** Adicione o método *score* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função da Questão 3 para calcular as distâncias para a matrix $\mathbf{W}$. Após isso, o método retornará o somatório das menores distâncias.

In [45]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)

    def score(self, X):
        d = Q03(X, self.W) # Calculo da matriz de distancias euclidianas
        d = np.apply_along_axis(min, 1, d) # atualizando a matriz das distancias, aplicando a função min, para achar as                                             # minimas distancias, por linha, na matriz distancias, utilizando a função                                               # apply_along_axis()
        return np.sum(d)
X = Q1
k = 5
tmax = 100
km = KMeans(k, tmax)

mu2 = [
    [0],
    [0]
]

covar2 = [
    [0.7457],
    [0.11515]
]
X1 = Q01(2,2,[20,4], param = (mu1, covar1))
X2 = Q01(2,2,[17, 48], param = (mu2, covar2))
km.fit(X,k)
print(km.fit(X,k))
print()
print(km.predict(X1))
print()
print(km.score(X2))

[[-0.27901689  1.67962557]
 [-0.19548028 -0.01123783]
 [ 1.10708983  0.94454607]
 [ 1.74023827  1.53873897]
 [ 0.5903043   0.43373026]]

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 4 2]

22.489926531979485
