# 1ª Avaliação de Programação Estatística com Python - 10/12/2019



   * Nome: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
   * Matrícula: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Questão 1 (1,0 ponto)** Implemente uma função que gere $C$ matrizes $\mathbf{X}_c^{n_c \times p}$, $c = 1, \ldots, C$, aleatoriamente, onde $n_c$ é a quantidade de linhas da matriz $\mathbf{X}_c$. As $p$ colunas de cada matriz $\mathbf{X}_c$ devem ser sorteadas de distribuições normais com médias e variâncias diferentes. A função deve então concatenar todas as matrizes geradas e retornar a matriz $\mathbf{X}^{n \times p}$, onde $n = \sum_{c=1}^C n_c$. <ins>Dica 1</ins>: A função pode receber como parâmetros uma lista com a quantidade de linhas de cada matriz $\mathbf{X}_c$, uma lista com as médias das normais usadas para gerar as colunas de cada matriz e outra lista com as variâncias correspondentes. <ins>Dica 2</ins>: considere usar a função *numpy.random.multivariate_normal*.

In [21]:
import numpy as np
def Q01(C, p, param):

    Xc = []

    for i in range(C):
        Xc.append(np.random.normal(param[0][i], param[1][i], (np.random.randint(50),p)))
    
    Xnp = np.vstack((Xc))

    return Xnp

mu = [
    [12,5],
    [8.5,7],
    [1,4]
]
covar = [
    [0.954,0.2],
    [0.37,0.87],
    [0.123,0.234]
]

Q1 = Q01(3,2, param = (mu, covar))

print(Q1)


[[12.79029993  4.84659598]
 [12.81709157  5.11318342]
 [12.56911221  4.90144054]
 [10.28847746  4.94541283]
 [11.07416449  4.99798251]
 [12.86300648  5.29050083]
 [11.69985552  5.05563473]
 [10.76796904  4.86314914]
 [10.76066568  5.26553155]
 [12.122051    5.34780933]
 [11.78454424  4.75268359]
 [12.06470392  4.92003207]
 [12.81045362  4.97627752]
 [12.08504762  4.83291245]
 [11.57943532  5.44981198]
 [12.169989    5.09139153]
 [13.11387582  4.87920577]
 [12.4970156   4.73154861]
 [ 8.47700529  6.99500403]
 [ 8.19236245  7.23577905]
 [ 8.45278313  8.95297942]
 [ 8.80872153  7.37058613]
 [ 8.38189472  8.12942754]
 [ 8.6453273   6.89002424]
 [ 7.64708864  6.88607935]
 [ 8.04974711  7.50953152]
 [ 8.84224954  6.56519918]
 [ 8.47195602  6.71428435]
 [ 8.72788322  6.0883508 ]
 [ 8.23289755  5.55254702]
 [ 8.14521623  6.61056525]
 [ 8.70857326  7.58157382]
 [ 7.94914972  7.04879342]
 [ 8.72273914  6.65884238]
 [ 8.32893853  6.76675906]
 [ 8.14406613  7.25968479]
 [ 8.73015298  6.48083428]
 

**Questão 2 (1,0 ponto)** Faça uma função que recebe uma matriz $\mathbf{X}^{n \times p}$ e um inteiro $k$ e retorna uma matriz $W^{k \times p}$, cujas linhas foram selecionadas aleatoriamente e sem reposição de $\mathbf{X}^{n \times p}$.

In [5]:
def Q02(Xnp, k):

    Wkp = []

    for j in range(k):
        
        Wkp.append(Xnp[np.random.randint(len(Xnp[:, 1]), size = 1)])

    Wkp = np.vstack(Wkp)
    
    return Wkp
Q2 = Q02(Q1, 4)

print(Q2)

[[-0.08651045 -1.92159687]
 [ 0.8552558  -0.55056028]
 [ 0.41126307 -0.31619269]
 [ 1.28861469 -0.9545045 ]]


**Questão 3 (1,0 ponto)** Faça uma função que recebe duas matrizes $\mathbf{X}^{n \times p}$ e $\mathbf{W}^{k \times p}$ e retorna a matriz de distâncias Euclidianas $\mathbf{D}^{n \times k}$ entre as linhas de $\mathbf{X}$ e as de $\mathbf{W}$.

In [6]:
def Q03(Xnp, Wkp):
    
    Dnk = np.zeros((len(Xnp), len(Wkp)))

    for i in range(len(Xnp)):
        for j in range(len(Wkp)):
            Dnk[i,j] = np.sqrt(np.sum((Xnp[i,:] - Wkp[j,:])**(2)))

    return Dnk

Q3 = Q03(Q1, Q2)

print(Q3)


[[2.82571787 1.86101188 1.41310757 2.44910436]
 [0.67905863 1.60364697 1.41598793 1.85128297]
 [1.6808037  0.5020535  0.         1.08498288]
 [3.0794515  1.52422466 1.40353812 1.94872331]
 [0.5548994  2.19708551 2.1565081  2.23576141]
 [0.9080949  1.96579576 2.19435723 1.6881249 ]
 [2.02335951 0.40812264 0.49810251 0.90925028]
 [2.48004817 0.97787176 0.80255353 1.48249164]
 [1.74572336 0.17010398 0.3713511  0.75608215]
 [1.41659212 0.84071968 0.44002275 1.34884054]
 [2.83936654 1.18221571 1.27626353 1.46239812]
 [1.48082484 0.19067395 0.56481258 0.54235985]
 [2.8390628  1.77383679 1.35123629 2.3551428 ]
 [2.96420759 1.31839407 1.36205739 1.6276673 ]
 [2.33253684 2.18421246 1.69226    2.73166421]
 [2.33660015 2.0521103  1.55392916 2.6127944 ]
 [2.12435237 1.27109204 0.77794455 1.86073032]
 [2.16210242 1.13643311 0.66849023 1.72881479]
 [1.65538073 1.35108164 0.88593481 1.87656366]
 [1.66332949 0.         0.5020535  0.59242794]
 [3.41833268 1.79482826 1.7711316  2.12180629]
 [3.09920324 

**Questão 4 (1,0 ponto)** Qual função de NumPy pode ser usada para obter para cada linha da matriz $\mathbf{D}$, retornada pela função da questão acima, a coluna que representa a menor distância da linha correspondente em $\mathbf{X}$ para as linhas de $\mathbf{W}$? Use a função para retornar essa informação.

In [11]:
Q4 = np.argmin(Q3, axis = 1)
print(Q4)

[2 0 2 2 0 0 1 2 1 2 1 1 2 1 2 2 2 2 2 1 2 2 2 3 2 2 0 2 3 2 0 2 2 2 2 1 2
 2 3]


**Questão 5 (2,0 pontos)** Faça uma função que atualiza as linhas de $\mathbf{W}$, fazendo com que cada linha assuma o valor médio das linhas de $\mathbf{X}$ para as quais a mesma foi a mais próxima. A função deve retornar a matriz $\mathbf{W}$ modificada. Use a função de NumPy mencionada na Questão 4.

In [8]:
def Q05(Xnp, Wkp, Dnk, c):
    k = np.argmin(Dnk, axis = 1)
    for i in range(c):
        X = Xnp[k == i,:]
        Wkp[i,:] = np.apply_along_axis(func1d = np.mean, arr = X, axis = 0)
    
    return Wkp

Q5 = Q05(Q1, Q2, Q3, 3)

print(Q5)

[[ 0.05547936 -2.00127687]
 [ 0.9954173  -0.14650358]
 [-0.13973946  0.44655926]
 [ 1.28861469 -0.9545045 ]]


**Questão 6 (1,5 pontos)** Implemente uma classe, chamada *KMeans*, cujo construtor define os seguintes atributos: $k$ e $t_{max}$. A classe deve conter um método *fit*, que recebe como parâmetro uma matriz $\mathbf{X}$. O método *fit* irá então seguir os seguintes passos:

  1. Use a função implementada na Questão 2 para obter a matriz $\mathbf{W}$ (note que o segundo parâmetro da função receberá como argumento um dos atributos definidos no construtor);
  2. Repita as operações abaixo $t_{max}$ vezes (note que isso é um atributo):
    1. Use a função da Questão 3 para calcular as distâncias entre $\mathbf{X}$ e $\mathbf{W}$
    2. Use a função da Questão 5 para atualizar as linhas de $\mathbf{W}$

Ao final do método *fit*, a matriz $\mathbf{W}$ resultante deve ser guardada como um atributo.

In [9]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax
    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        return new_W
X = Q1
k = 4
tmax = 100
km = KMeans(k, tmax)

print(km.fit(X, k))


[[-0.62493594  0.02931093]
 [-0.3838235   1.17216748]
 [ 0.62128462 -0.43712767]
 [ 0.21023149 -1.91936268]
 [ 1.33846619  0.73192944]]


**Questão 7 (1,0 ponto)** Adicione o método *predict* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função de NumPy mencionada na Questão 4 para retornar os índices das linhas de $\mathbf{W}$ mais próximas às linhas de $\mathbf{X}$.

In [10]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)
    
X = Q1
k = 5
tmax = 100
km = KMeans(k, tmax)
X1 = Q01(2,2, param = ((0,1), (0,1)))

print(km.fit(X,k) , km.predict(X1))


[[ 0.62128462 -0.43712767]
 [ 0.21023149 -1.91936268]
 [-0.62493594  0.02931093]
 [ 1.33846619  0.73192944]
 [-0.3838235   1.17216748]]


**Questão 8 (1,5 ponto)** Adicione o método *score* à classe *KMeans*. O método irá receber uma nova matriz $\mathbf{X}$ e irá usar a função da Questão 3 para calcular as distâncias para a matrix $\mathbf{W}$. Após isso, o método retornará o somatório das menores distâncias.

In [ ]:
class KMeans:
    def __init__(self, k, tmax):
        self.k, self.tmax = k, tmax

    def fit(self,X, k):
        W = Q02(X,k)
        for i in range(self.tmax):
            dists = Q03(X, W)
            new_W = Q05(X, W, dists, k)
        
        self.W = W

        return new_W

    def predict(self,X):
        dists = Q03(X, self.W)
        return np.argmin(dists , axis = 1)

    def score(self, X):
        d = Q03(X, self.W)
        d = np.apply_along_axis(min, 1, d)
        return np.sum(d)
X = Q1
k = 5
tmax = 100
km = KMeans(k, tmax)
X1 = Q01(2,2, param = ((0,1), (0,1)))
X2 = Q01(2,2, param = ((0,1), (0,1)))
km.fit(X,k)
print(km.fit(X,k), km.predict(X1), km.score(X2))